# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/styx_lwip_test.xdc

# Block Designs: bd/top_level/top_level.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level || ORIG_REF_NAME==top_level} -quiet] -quiet

# IP: bd/top_level/ip/top_level_processing_system7_0_0/top_level_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_processing_system7_0_0 || ORIG_REF_NAME==top_level_processing_system7_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_proc_sys_reset_0_0/top_level_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_proc_sys_reset_0_0 || ORIG_REF_NAME==top_level_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_util_reduced_logic_0_0/top_level_util_reduced_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_util_reduced_logic_0_0 || ORIG_REF_NAME==top_level_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_gmii_to_rgmii_0_0/top_level_gmii_to_rgmii_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_gmii_to_rgmii_0_0 || ORIG_REF_NAME==top_level_gmii_to_rgmii_0_0} -quiet] -quiet

# XDC: /home/user/Desktop/Styx_airbornesonar/Styx_airbornesonar.gen/sources_1/bd/top_level/top_level_ooc.xdc
